blueprint:
  name: Sun-segmented light brightness (3 segments)
  description: >
    Control a light's brightness based on 3 logical segments defined by
    clock times and/or sun elevation angles, with linear ramps between
    segment brightnesses.
  domain: automation

  input:
    light_target:
      name: Target light
      selector:
        entity:
          domain: light

    # -------- Segment 1 --------
    seg1_start_time:
      name: Segment 1 start - clock time (optional)
      description: 'Format "HH:MM" or "HH:MM:SS". Leave blank to ignore.'
      default: "16:00:00"
      selector:
        text: {}

    seg1_start_elev:
      name: Segment 1 start - sun elevation (optional)
      description: 'Degrees. Example: -6 for civil dusk. Leave blank to ignore.'
      default: ""
      selector:
        text: {}

    seg1_brightness:
      name: Segment 1 starting brightness (%)
      default: 10
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

    # -------- Segment 2 --------
    seg2_start_time:
      name: Segment 2 start - clock time (optional)
      description: 'Format "HH:MM" or "HH:MM:SS". Leave blank to ignore.'
      default: ""
      selector:
        text: {}

    seg2_start_elev:
      name: Segment 2 start - sun elevation (optional)
      description: 'Degrees. Example: 5 for morning golden hour. Leave blank to ignore.'
      default: "6"
      selector:
        text: {}

    seg2_brightness:
      name: Segment 2 starting brightness (%)
      default: 100
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

    # -------- Segment 3 --------
    seg3_start_time:
      name: Segment 3 start - clock time (optional)
      description: 'Format "HH:MM" or "HH:MM:SS". Leave blank to ignore.'
      default: "22:30"
      selector:
        text: {}

    seg3_start_elev:
      name: Segment 3 start - sun elevation (optional)
      description: 'Degrees. Example: -2 for late dusk. Leave blank to ignore.'
      default: "-18"
      selector:
        text: {}

    seg3_brightness_start:
      name: Segment 3 starting brightness (%)
      default: 80
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

    seg3_end_time:
      name: Segment 3 end - clock time (optional)
      description: 'Format "HH:MM" or "HH:MM:SS". Leave blank to ignore.'
      default: "23:30"
      selector:
        text: {}

    seg3_end_elev:
      name: Segment 3 end - sun elevation (optional)
      description: 'Degrees. Example: -12 for astronomical. Leave blank to ignore.'
      default: ""
      selector:
        text: {}

    seg3_brightness_end:
      name: Segment 3 ending brightness (%)
      default: 5
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

mode: single

trigger:
  - platform: time_pattern
    minutes: "/5"

variables:
  light_target: !input light_target

  # Raw blueprint inputs
  seg1_clock: !input seg1_start_time
  seg1_elev_str: !input seg1_start_elev
  seg1_brightness: !input seg1_brightness

  seg2_clock: !input seg2_start_time
  seg2_elev_str: !input seg2_start_elev
  seg2_brightness: !input seg2_brightness

  seg3_clock: !input seg3_start_time
  seg3_elev_str: !input seg3_start_elev
  seg3_brightness_start: !input seg3_brightness_start

  seg3_end_clock: !input seg3_end_time
  seg3_end_elev_str: !input seg3_end_elev
  seg3_brightness_end: !input seg3_brightness_end

  # Main calculation: target brightness (0-100) or 'none' if no segment
  target_brightness: >-
    {% macro sun_elevation_at_datetime(dt) %}
      {% set t = as_datetime(dt) %}
      {% if t is none %}
        {{ none }}
      {% else %}
        {% set lat = state_attr('zone.home', 'latitude') | float %}
        {% set lon = state_attr('zone.home', 'longitude') | float %}
        {% set deg2rad = pi / 180 %}
        {% set rad2deg = 180 / pi %}

        {# Julian Day #}
        {% set jd = t.timestamp() / 86400 + 2440587.5 %}
        {% set T = (jd - 2451545.0) / 36525 %}

        {# NOAA solar terms #}
        {% set L0 = 280.46646 + 36000.76983 * T %}
        {% set M  = 357.52911 + 35999.05029 * T %}
        {% set C  =
          (1.914602 - 0.004817 * T - 0.000014 * T * T) * sin(M * deg2rad)
          + (0.019993 - 0.000101 * T) * sin(2 * M * deg2rad)
          + 0.000289 * sin(3 * M * deg2rad)
        %}
        {% set lambda = L0 + C %}
        {% set lambda_r = lambda * deg2rad %}

        {% set eps = 23.439291 - 0.0130042 * T %}
        {% set eps_r = eps * deg2rad %}

        {# Declination #}
        {% set dec = asin(sin(eps_r) * sin(lambda_r)) %}
        {% set lat_r = lat * deg2rad %}

        {# Sidereal time #}
        {% set GST = 280.46061837 + 360.98564736629 * (jd - 2451545) %}
        {% set LST = GST + lon %}
        {% set LST_r = LST * deg2rad %}

        {# Right ascension #}
        {% set ra = atan2(
          cos(eps_r) * sin(lambda_r),
          cos(lambda_r)
        ) %}

        {# Hour angle #}
        {% set H = LST_r - ra %}

        {# Elevation #}
        {% set elev_r = asin(
          sin(lat_r) * sin(dec) +
          cos(lat_r) * cos(dec) * cos(H)
        ) %}

        {{ (elev_r * rad2deg) | float }}
      {% endif %}
    {% endmacro %}

    {% macro sun_time_at_elevation(target_elev, ref_dt) %}
      {% set target = target_elev | float %}
      {% set ref = as_datetime(ref_dt) %}
      {% if ref is none %}
        None
      {% else %}
        {% set ns = namespace(best_t=ref, best_diff=999999) %}

        {# --- coarse search (10min steps) --- #}
        {% set start = ref - timedelta(hours=12) %}
        {% for i in range(0, 24*6 + 1) %}
          {% set t_candidate = start + timedelta(minutes=10*i) %}
          {% set elev = sun_elevation_at_datetime(t_candidate) | float %}
          {% set diff = (elev - target) | abs %}
          {% if diff < ns.best_diff %}
            {% set ns.best_diff = diff %}
            {% set ns.best_t = t_candidate %}
          {% endif %}
        {% endfor %}

        {# --- fine search (1min steps) --- #}
        {% set ns.best_diff = 999999 %}
        {% set fine_start = ns.best_t - timedelta(minutes=20) %}
        {% for i in range(0, 41) %}
          {% set t_candidate = fine_start + timedelta(minutes=i) %}
          {% set elev = sun_elevation_at_datetime(t_candidate) | float %}
          {% set diff = (elev - target) | abs %}
          {% if diff < ns.best_diff %}
            {% set ns.best_diff = diff %}
            {% set ns.best_t = t_candidate %}
          {% endif %}
        {% endfor %}

        {{ as_timestamp(ns.best_t) }}
      {% endif %}
    {% endmacro %}

    {% macro next_clock_ts(clock_str) %}
      {% set s = (clock_str or '') | trim %}
      {% if s == "" %}
        None
      {% else %}
        {% set parts = s.split(":") %}
        {% set h = parts[0] | int %}
        {% set m = (parts[1] | int) if parts|count > 1 else 0 %}
        {% set sec = (parts[2] | int) if parts|count > 2 else 0 %}
        {% set now_dt = now().replace(microsecond=0) %}
        {% set candidate = now_dt.replace(hour=h, minute=m, second=sec) %}
        {% if candidate < now_dt %}
          {% set dt = candidate + timedelta(days=1) %}
        {% else %}
          {% set dt = candidate %}
        {% endif %}
        {{ as_timestamp(dt) }}
      {% endif %}
    {% endmacro %}

    {% macro elev_ts(elev_str) %}
      {% set s = (elev_str or '') | trim %}
      {% if s == "" %}
        None
      {% else %}
        {% set ref = now().replace(hour=23,minute=59,second=0,microsecond=0) %}
        {{ sun_time_at_elevation(s|float, ref)|trim }}
      {% endif %}
    {% endmacro %}

    {% macro earliest(a, b) %}
      {% if a == "None" or a is none %}
        {% if b == "None" or b is none %}
          None
        {% else %}
          {{ b }}
        {% endif %}
      {% else %}
        {% if b == "None" or b is none %}
          {{ a }}
        {% else %}
          {{ (a|float, b|float) | min }}
        {% endif %}
      {% endif %}
    {% endmacro %}

    {% set now_ts = as_timestamp(now()) %} {% set seg1_clock_ts =
    next_clock_ts(seg1_clock)|trim %} {% set seg1_elev_ts =
    elev_ts(seg1_elev_str)|trim %} {% set seg1_start =
    earliest(seg1_clock_ts, seg1_elev_ts)|trim %}
      
    {% set seg2_clock_ts = next_clock_ts(seg2_clock)|trim %} {% set
    seg2_elev_ts = elev_ts(seg2_elev_str)|trim %} {% set seg2_start =
    earliest(seg2_clock_ts, seg2_elev_ts)|trim %}
      
    {% set seg3_clock_ts = next_clock_ts(seg3_clock)|trim %} {% set
    seg3_elev_ts = elev_ts(seg3_elev_str)|trim %} {% set seg3_start =
    earliest(seg3_clock_ts, seg3_elev_ts)|trim %}
      
    {% set seg3_end_clock_ts = next_clock_ts(seg3_end_clock)|trim %} {% set
    seg3_end_elev_ts = elev_ts(seg3_end_elev_str)|trim %} {% set seg3_end =
    earliest(seg3_end_clock_ts, seg3_end_elev_ts)|trim %}
      
    {% set b1_start = seg1_brightness | float %} {% set b2_start =
    seg2_brightness | float %} {% set b3_start = seg3_brightness_start |
    float %} {% set b3_end = seg3_brightness_end | float %} {% set in_seg1 =
    seg1_start != "None" and seg2_start != "None" and (seg1_start | float)
    <= now_ts < (seg2_start | float) %} {% set in_seg2 = seg2_start !=
    "None" and seg3_start != "None" and (seg2_start | float) <= now_ts <
    (seg3_start | float) %} {% set in_seg3 = seg3_start != "None" and
    seg3_end != "None" and (seg3_start | float) <= now_ts < (seg3_end |
    float) %}

    {# If we are in no active segment, do nothing #} {% if not (in_seg1 or
    in_seg2 or in_seg3) %}
      None
    {% else %}

      {# ---------------- Pick segment start/end + brightness ---------------- #}
      {% if in_seg1 %}
        {% set t0 = seg1_start | float %}
        {% set t1 = seg2_start | float %}
        {% set b0 = b1_start %}
        {% set b1 = b2_start %}
      {% elif in_seg2 %}
        {% set t0 = seg2_start | float %}
        {% set t1 = seg3_start | float %}
        {% set b0 = b2_start %}
        {% set b1 = b3_start %}
      {% else %}
        {% set t0 = seg3_start | float %}
        {% set t1 = seg3_end | float %}
        {% set b0 = b3_start %}
        {% set b1 = b3_end %}
      {% endif %}

      {# ---- Compute position in segment ---- #}
      {% set duration = t1 - t0 %}
      {% if duration <= 0 %}
        {% set p = 0 %}
      {% else %}
        {% set p = (now_ts - t0) / duration %}
        {% set p = 0 if p < 0 else (1 if p > 1 else p) %}
      {% endif %}

      {# ---- LERP brightness ---- #}
      {% set brightness = b0 + (b1 - b0) * p %}

      {# ---- Check current light brightness (0-100) ---- #}
      {% set raw = state_attr(light_target, "brightness") %}
      {% if raw is none %}
        {% set current_pct = 0 %}
      {% else %}
        {% set current_pct = (raw | float) / 255 * 100 %}
      {% endif %}
      
      {# ---- Rule: Segments 1 & 2 never dim ---- #}
      {% if (in_seg1 or in_seg2) and brightness < current_pct %}
        None
      {% else %}
        {{ brightness }}
      {% endif %}
    {% endif %}
    
action:
  - service: logbook.log
    data:
      name: "Sun Brightness Blueprint Debug"
      message: >
        light_target = {{ light_target }}
        seg1_clock = "{{ seg1_clock }}"
        seg1_elev_str = "{{ seg1_elev_str }}"
        seg1_brightness = {{ seg1_brightness }}
  
        seg2_clock = "{{ seg2_clock }}"
        seg2_elev_str = "{{ seg2_elev_str }}"
        seg2_brightness = {{ seg2_brightness }}
  
        seg3_clock = "{{ seg3_clock }}"
        seg3_elev_str = "{{ seg3_elev_str }}"
        seg3_brightness_start = {{ seg3_brightness_start }}
  
        seg3_end_clock = "{{ seg3_end_clock }}"
        seg3_end_elev_str = "{{ seg3_end_elev_str }}"
        seg3_brightness_end = {{ seg3_brightness_end }}
  
        seg1_clock_ts = {{ seg1_clock_ts }}
        seg1_elev_ts = {{ seg1_elev_ts }}
        seg1_start = {{ seg1_start }}
  
        seg2_clock_ts = {{ seg2_clock_ts }}
        seg2_elev_ts = {{ seg2_elev_ts }}
        seg2_start = {{ seg2_start }}
  
        seg3_clock_ts = {{ seg3_clock_ts }}
        seg3_elev_ts = {{ seg3_elev_ts }}
        seg3_start = {{ seg3_start }}
  
        seg3_end_clock_ts = {{ seg3_end_clock_ts }}
        seg3_end_elev_ts = {{ seg3_end_elev_ts }}
        seg3_end = {{ seg3_end }}
  
        in_seg1 = {{ in_seg1 }}
        in_seg2 = {{ in_seg2 }}
        in_seg3 = {{ in_seg3 }}
  
        now_ts = {{ now_ts }}
  
        t0 = {{ t0 if (in_seg1 or in_seg2 or in_seg3) else 'none' }}
        t1 = {{ t1 if (in_seg1 or in_seg2 or in_seg3) else 'none' }}
        duration = {{ duration if (in_seg1 or in_seg2 or in_seg3) else 'none' }}
        p = {{ p if (in_seg1 or in_seg2 or in_seg3) else 'none' }}
  
        current_pct = {{ current_pct if (in_seg1 or in_seg2 or in_seg3) else 'none' }}
        brightness = {{ brightness if (in_seg1 or in_seg2 or in_seg3) else 'none' }}
  
        target_brightness = {{ target_brightness }}
  - choose:
      - conditions: "{{ target_brightness is not none }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_target }}"
            data:
              brightness_pct: "{{ target_brightness | float | round(0) }}"
              transition: 30
    default: []
